[feat] 최근 검색어 저장을 위한 Room 셋팅
Health-Food-Me/Health-Food-Me-Android pull request #16
Opened 2022-07-06 17:41 UTC by mdb1217

## Related issue 🚀
- closed #14 

## Work Description 💚
- 룸 기초세팅 완료했습니다! 기획단에서 중복 키워드도 DB에 허용한다고해서, 키 값은 따로 뒀어요!
- Database, Entity, DAO, DI 셋팅
- 애플리케이션 파일이 Manifest에 적용이 안되어있어서 그것도 적용해줬어요!

2022-07-06 18:10 UTC, mdb1217 commented
우선 PR 제목 컨벤션 양식 지켜주시면 감사하겠습니다 :) 작업하신다고 수고많았어요😊😊

2022-07-06 22:17 UTC, youngjinc approved these changes
확인했습니다! 수고 많으셨습니다~

2022-07-06 22:17 UTC, youngjinc commented on app/src/main/AndroidManifest.xml
> +        android:name=".HFMApplication"
👍

2022-07-07 01:56 UTC, l2hyunwoo requested changes
지나가던 참새: 아ㅋㅋ 방앗간 못참취~

2022-07-07 01:56 UTC, l2hyunwoo commented on app/src/main/java/org/helfoome/data/local/dao/SearchDao.kt
> +    fun getAll(): List<SearchData>
suspend로 변경해야 Main thread safety할 것 같습니다.

2022-07-07 03:54 UTC, lee989898 approved these changes
많이 배웠습니다!

2022-07-07 03:54 UTC, lee989898 commented on app/src/main/java/org/helfoome/data/local/dao/SearchDao.kt
> +    fun getAll(): List<SearchData>
만약에 flow나 livedata 쓰는 경우에는 suspend를 안써도 괜찬을까요?

2022-07-07 03:54 UTC, lee989898 commented on app/src/main/java/org/helfoome/data/local/dao/SearchDao.kt
> +    @Insert(onConflict = OnConflictStrategy.IGNORE)
OnConflictStrategy.IGNORE이 가장 빠른건지 궁금합니다!!

OnConflictStrategy.ABORT | 충돌이 발생할 경우 처리 중단
OnConflictStrategy.FAIL | 충돌이 발생할 경우 실패처리
OnConflictStrategy.IGNORE | 충돌이 발생할 경우 무시
OnConflictStrategy.REPLACE | 충돌이 발생할 경우 덮어쓰기
OnConflictStrategy.ROLLBACK | 충돌이 발생할 경우 이전으로 되돌리기

2022-07-07 03:54 UTC, lee989898 commented on app/src/main/java/org/helfoome/data/local/database/HFMDatabase.kt
> +@Database(entities = [SearchData::class], version = 1, exportSchema = false)
exportSchema = false 이 부분은 개발 끝나면 없애주나요?

2022-07-07 04:48 UTC, l2hyunwoo commented on app/src/main/java/org/helfoome/data/local/dao/SearchDao.kt
> +    fun getAll(): List<SearchData>
suspend modifier를 사용하게 되는 경우 Main thread safe하게 빌드된 코루틴 스코프내에서 데이터 입출력 작업을 처리할 수 있습니다.

Flow는 flowOn으로 수행되는 코루틴 컨텍스트를 바꿀순 있다치더라도 LiveData는 무조건 MainThread에서 post되거나 동기적으로 데이터가 전달되기에 그다지 추천드리고 싶지는 않네요.

그리고 flow에서 디스패처를 바꾸는 방법보단 해당 작업이 백그라운드 스레드에서 수행됨을 보장하고 ViewModel/View 단에서는 웬만하면 Main Thread에서 모든작업을 처리하라는 가이드라인이 있습니다. Android App Architecture의 UI Layer 설명을 살펴보세요.

2022-07-07 04:50 UTC, lee989898 commented on app/src/main/java/org/helfoome/data/local/dao/SearchDao.kt
> +    fun getAll(): List<SearchData>
친절한 설명 감사합니다!! UI Layer 살펴보겠습니다

2022-07-07 09:00 UTC, mdb1217 commented on app/src/main/java/org/helfoome/data/local/dao/SearchDao.kt
> +    fun getAll(): List<SearchData>
suspend 키워드 까먹은듯 ㅋㅋㅋ.... 고맙긴하데.. 너 안 바쁘니 현우야..

2022-07-07 09:02 UTC, mdb1217 commented on app/src/main/java/org/helfoome/data/local/dao/SearchDao.kt
> +    @Insert(onConflict = OnConflictStrategy.IGNORE)
우선 기획이 변경될 가능성이 있다고 했지만, 

**OnConflictStrategy.IGNORE** 이걸 쓴 이유는 키값이 겹쳐도..(엥간 롱타입이라 중복 안될 것 같긴한데..ㅋㅋㅋㅋ) 데이터를 살리기 위해서 이렇게 셋팅을 해놓은 거에요..! 중복되는 키워드도 허용한다고해서 ㅎㅅㅎ

2022-07-07 09:07 UTC, mdb1217 commented on app/src/main/java/org/helfoome/data/local/database/HFMDatabase.kt
> +@Database(entities = [SearchData::class], version = 1, exportSchema = false)
그냥... 스키마 정보 제공하라는 경고 보기싫어서.. 추가한건데.........

원래 아름다운 구조는 스키마 변경된 기록들 json으로 만들어서 남겨야 되는 걸로 알긴하지만.. 아마 일단은 계속 이렇게 둘 것 같아요!

2022-07-07 10:31 UTC, merged